name: Linter to check for spelling of phrases in markdown files

on:
  pull_request:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    name: Linter to check for spelling of phrases in markdown files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To retrieve the current commit.

      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with:
          # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`
          # since_last_remote_commit: true
          files: |
            **.md

      - name: Read and check wrongly spelled words
        id: read-and-check-words
        run: |
          # Read and check wrongly spelled words from the file
          mapfile -t wrongly_spelled_words < .github/wrongly_spelled_words.txt
          echo "Wrongly spelled words: ${wrongly_spelled_words[*]}"

          # Check for wrongly spelled words in each .md file
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            for word in "${wrongly_spelled_words[@]}"; do
              if grep -q "$word" "$file"; then
                echo "Wrong spelling of '$word' found in $file"
                exit 1
              fi
            done
          done
        shell: bash
