name: Check modified MD files for prohibited phrases

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-phrases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install the ripgrep tool for searching files
      - name: Install ripgrep
        run: sudo apt update && sudo apt install ripgrep

      # Identify modified MD files in the pull request
      - name: Get modified MD files
        id: modified-md-files
        run: git diff --name-only HEAD~1..HEAD | grep '\.md$'

      # Check each modified MD file for prohibited phrases
      - name: Check for prohibited phrases
        id: check-phrases
        if: steps.modified-md-files.outputs.stdout != ''
        run: |
          prohibited_phrases="phrase1 phrase2 phrase3"
          modified_md_files=$(echo "${{ steps.modified-md-files.outputs.stdout }}")

          for file in $modified_md_files; do
            if rg -F "${prohibited_phrases}" "$file"; then
              echo "Prohibited phrase found in file: $file"
              exit 1
            fi
          done

      # Set the job failure status if any prohibited phrases are found
      - name: Set job failure if phrases found
        id: set-job-failure
        if: steps.check-phrases.outcome != 'success'
        run: echo "::set-output name=failure::Prohibited phrases found in modified MD files"
