name: Linter to check for spelling of phrases in markdown files

on:
  pull_request:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    name: Linter to check for spelling of phrases in markdown files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To retrieve the current commit.

      - name: Read and check wrongly spelled words
        id: read-and-check-words
        run: |
          # Read and check wrongly spelled words from the file
          mapfile -t wrongly_spelled_words < .github/wrongly_spelled_words.txt
          echo "Wrongly spelled words: ${wrongly_spelled_words[*]}"

          # Check for wrongly spelled words in each .md file
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            for word in "${wrongly_spelled_words[@]}"; do
              if grep -q "$word" "$file"; then
                echo "Wrong spelling of '$word' found in $file"
                exit 1
              fi
            done
          done
        shell: bash
