name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Linter to check for spelling of phrases in markdown files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To retrieve the current commit.

      # - name: Get changed files
      #   id: changed-files
      #   uses: tj-actions/changed-files@v40

      #   # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`
      #   with:
      #     since_last_remote_commit: true

      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with:
          since_last_remote_commit: true
          files: |
            **.md

      - name: Check for wrongly spelled words in all of the changed markdown files
        run: |
          wrongly_spelled_words=("availability risk" "Availability risk" "Latent availability risk" "addon" "Add-on" "add-on" "add on")

          # Check for wrongly spelled words in each .md file
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            for phrase in "${wrongly_spelled_words[@]}"; do
              if grep -q "$phrase" "$file"; then
                echo "Wrong spelling of '$phrase' found in $file"
                exit 1
              fi
            done
          done
