name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check modified files
        id: check-files
        run: |
          # Get the list of modified files
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Filter files with .md extension
          md_files=$(echo "$files" | grep '\.md$' || true)

          # Set an output variable with the list of .md files
          echo "::set-output name=md_files::$md_files"

      - name: Check for forbidden phrases
        id: check-phrases
        run: |
          forbidden_phrases=("availability risk")

          # Check for forbidden phrases in each .md file
          for file in ${{ steps.check-files.outputs.md_files }}; do
            for phrase in "${forbidden_phrases[@]}"; do
              if grep -q "$phrase" "$file"; then
                echo "Error: Forbidden phrase '$phrase' found in file $file"
                echo "::set-output name=forbidden_found::true"
              fi
            done
          done

      - name: Fail if forbidden phrases found
        if: steps.check-phrases.outputs.forbidden_found == 'true'
        run: exit 1
