name: Linter to check for spelling of phrases in markdown files

on:
  pull_request:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    name: Linter to check for spelling of phrases in markdown files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To retrieve the current commit.

      - name: Read wrongly spelled words from file
        id: read-wrongly-spelled-words
        run: |
          mapfile -t wrongly_spelled_words < .github/wrongly_spelled_words.txt
          for word in "${wrongly_spelled_words[@]}"; do
            echo "Wrongly spelled word: $word"
          done
        shell: bash

      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with:
          since_last_remote_commit: true
          files: |
            **.md

      - name: Check for wrongly spelled words in all of the changed markdown files
        run: |
          # Check for wrongly spelled words in each .md file
          for word in "${wrongly_spelled_words[@]}"; do
            echo "Wrongly spelled word: $word"
          done
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            for word in "${wrongly_spelled_words[@]}"; do
              if grep -q "$word" "$file"; then
                echo "Wrong spelling of '$word' found in $file"
                exit 1
              fi
            done
          done
